
services:
  - type: web
    name: silver-scanner-enterprise-live-scraping
    runtime: python
    buildCommand: pip install -r requirements.txt && playwright install chromium
    startCommand: gunicorn backend.main:app
    plan: free
